language: python
sudo: required
services:
  - cassandra
  - redis-server
  - mysql

python:
  - 2.7
#  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
#  - 3.7-dev
#  - pypy  # Cassandra suddenly failing to find hosts on Travis, 21 April 2018. Not sure why.
  - pypy3

before_install:
  - mysql -e 'CREATE DATABASE eventsourcing;'

install:
- pip install -U pip wheel
- CASS_DRIVER_NO_CYTHON=1 pip install -e .[testing]
- pip install pymysql
- pip install mysql-connector-python-rf
- pip install python-coveralls

env:
  global:
    - CASSANDRA_HOSTS=127.0.0.1

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage run --concurrency=multiprocessing -m unittest discover eventsourcing.tests -v;
  fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      python -m unittest discover eventsourcing.tests -v;
  fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage combine;
      coveralls;
  fi
