language: python
sudo: required
services:
  - cassandra
  - redis-server
  - mysql
  - postgresql

python:
#  - 3.5  # we use f-strings
  - 3.6
  - 3.7-dev
  - pypy3


before_install:
  - mysql -e 'CREATE DATABASE eventsourcing;'

before_script:
  - psql -c 'create database eventsourcing;' -U postgres

install:
- pip install -U pip wheel
- CASS_DRIVER_NO_CYTHON=1 pip install -e .[testing]
- pip install pymysql
- pip install mysql-connector-python-rf
- pip install python-coveralls

env:
  global:
    - CASSANDRA_HOSTS=127.0.0.1
    - MYSQL_USER=travis
    - POSTGRES_USER=postgres

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage run --concurrency=multiprocessing -m unittest discover eventsourcing.tests -v;
  fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      python -m unittest discover eventsourcing.tests -v;
  fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage combine;
      coveralls;
  fi
