dist: xenial   # required for Python >= 3.7
language: python
#sudo: required
services:
  - cassandra
  - redis-server
  - mysql
  - postgresql

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"  # 3.8 development branch
  - "pypy3.5"

before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz && tar -xvzf
    apache-cassandra-3.11.2-bin.tar.gz && sudo sh apache-cassandra-3.11.2/bin/cassandra
YAML

before_script:
  - mysql -e 'CREATE DATABASE eventsourcing;'
  - psql -c 'create database eventsourcing;' -U postgres

install:
- pip install -U pip wheel
- CASS_DRIVER_NO_CYTHON=1 pip install -e .[testing]
- pip install pymysql
- pip install mysql-connector-python-rf
- pip install python-coveralls

env:
  global:
    - CASSANDRA_HOSTS=127.0.0.1
    - MYSQL_USER=travis
    - POSTGRES_USER=postgres

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage run --concurrency=multiprocessing -m unittest discover eventsourcing.tests -v;
  fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      python -m unittest discover eventsourcing.tests -v;
  fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      coverage combine;
      coveralls;
  fi
