# To use this Docker Compose file in PyCharm, just add a new Docker Compose
# project interpreter, and pick "all_eventsourcing_requirements" as the service. It
# will take a little while to download and build everything, then all tests should pass.
# Please note, both MySQL and Cassandra containers need a little while to get started
# first time the containers are run, so connections might not work immediately.
version: '2'
services:
    all_eventsourcing_requirements:
        build: .
        image: "eventsourcing_requirements:latest"
        volumes:
            - .:/app
        links:
            - cassandra
            - mysql
            - redis
        environment:
            CASSANDRA_HOSTS: cassandra
            MYSQL_HOST: mysql
            MYSQL_USER: eventsourcing
            MYSQL_PASSWORD: eventsourcing
            REDIS_HOST: redis

    cassandra:
        image: "cassandra:latest"

    mysql:
        image: "mysql:latest"
        environment:
          MYSQL_ROOT_PASSWORD: eventsourcing
          MYSQL_USER: eventsourcing
          MYSQL_PASSWORD: eventsourcing
          MYSQL_DATABASE: eventsourcing

    redis:
        image: "redis:latest"
